version: "3"

volumes:
  db:
    driver: local

services:
    db:
        image: postgres
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
        ports:
            - "5432:5432"
        volumes:
            - db:/var/lib/postgresql/data
    redis-server:
        restart: on-failure
        image: "redis"
    back:
        restart: on-failure
        build:
            context: ./nodejs
    goback:
        restart: on-failure
        build:
            context: ./go
    nginx:
        restart: on-failure
        build:
            context: ./
            dockerfile: ./frontend/Dockerfile
        ports:
            - "9050:80"